# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39f6d1be86569e7b15105c56f42b6bbf3d4a623e7a140876038116c53fdd1497e3d17f3c8746cb35f578f71a61e55bb884fef26c788e9743d1d77c403bf9178

test:
  secret_key_base: 1158efc5e36bed6cf1b0e32622122dd8018ebbf8c58531e382ceddca8dc085edec162fb974df78ce644f9055aa6079b1e56ab4fdef95fd202fe234ca1ec1e7e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
